# Generated by Django 4.0.3 on 2022-03-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='remitter',
            new_name='email',
        ),
    ]
